spring.application.name=organizational_chart_service

server.port=8082
spring.datasource.url=jdbc:h2:file:./data
spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:mysql://localhost:3306/ocsdb
#spring.datasource.username=ocsdbuser
#spring.datasource.password=changeit4
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/sts
kc.authServerUrl=http://localhost:8080
kc.realm=sts
kc.externalConfigFilePath=D:\\Software Engineering\\Projects\\simple-ticketing-system\\deps\\docker-compose-dev\\keycloak-initializer-data\\result.json
kc.clientId=ocs-api
#kc.clientSecret=cgRxn1JdKBUXCsduA3jptqB3roRYnP7i
#kc.wuiClientId=ocs-wui
#kc.wuiClientRootUrl=http://localhost:4200
#kc.tmpAdminUsername=admin
#kc.tmpAdminPassword=admin
#kc.initializeKcAdminUser=false

logging.level.ir.mojir=TRACE