spring.application.name=organizational_chart_service

server.port=8082
spring.datasource.url=jdbc:h2:file:./data
spring.jpa.hibernate.ddl-auto=update
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/cbi
kc.realm=cbi
kc.clientId=ocs-api
kc.clientSecret=cgRxn1JdKBUXCsduA3jptqB3roRYnP7i
kc.wuiClientId=ocs-wui
kc.wuiClientRootUrl=http://localhost:4200
kc.tmpAdminUsername=admin
kc.tmpAdminPassword=admin
kc.initializeKcAdminUser=false

logging.level.ir.mojir=TRACE