spring.application.name=organizational_chart_service

server.port=8081
spring.datasource.url=jdbc:h2:file:./data
spring.jpa.hibernate.ddl-auto=update
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/cbi
kc.clientId=ocs-api
kc.clientSecret=cgRxn1JdKBUXCsduA3jptqB3roRYnP7i